#!/cluster/home/een023/.virtualenvs/p3/bin/python

"""Generate aggregated netCDF files.

Send in a path to .nc files and the name of the files. Either as a list of many files or
with the asterisk (wildcard) notation, `"*.nc"`. Note that when using the wildcard
notation the string must be wrapped in quotation marks like in the above example.

Then creates a summary file for temperature or any valid attribute.
Usage:
    gen_temp -p look/here -i one.nc two.nc -sp input -o output_name -y -a ATTR
"""


import argparse
import datetime
import glob
import os
import sys
from typing import List, Union

import xarray as xr

parser = argparse.ArgumentParser(
    description="Create a file containing only the temperature variable.",
    formatter_class=argparse.ArgumentDefaultsHelpFormatter,
)
parser.add_argument("-p", "--path", type=str, default=".", help="path to .nc files")
parser.add_argument(
    "-sp",
    "--savepath",
    type=str,
    default="input",
    help="path to where the .nc file is saved",
)
parser.add_argument(
    "-i",
    "--input",
    type=str,
    nargs="+",
    help='input .nc files. Use quotes around *, e.g. "*.nc".',
)
parser.add_argument("-o", "--output", help="output .nc files")
parser.add_argument(
    "-y",
    "--year",
    action="store_true",
    help="If given, a 12 month running average is computed.",
)
parser.add_argument(
    "-a",
    "--attributes",
    type=str,
    nargs="+",
    default=["TREFHT"],
    help="List of attributes of netCDF file",
)

args = parser.parse_args()
# Correct the input argument
if args.input is None:
    raise ValueError("you must give the input files")
# Correct the output argument
if args.output is None:
    output = datetime.date.today().strftime("%Y%m%d")
else:
    output = args.output
if output.split(".")[-1] != "nc":
    output += ".nc"
# Correct the path argument
if args.path is not None:
    path = args.path + "/" if args.path[-1] != "/" else args.path
else:
    path = ""
# Combine the path with all files
inputs = [
    f"{path}{file}"
    if file.split(".")[-1] == "nc" or "*" in file
    else f"{path}{file}.nc"
    for file in args.input
]
# If an asterisk (*) is used, all other files are discarded
the_input: Union[str, List[str]]
if any("*" in f for f in inputs):
    val = inputs[[i for i, s in enumerate(inputs) if "*" in s][0]]
    the_input = str(val)
    if not glob.glob(the_input):
        print(f"I could not find {the_input}")
        print("Exiting...")
        sys.exit()
else:
    the_input = inputs
    for input_ in the_input:
        if not glob.glob(input_):
            print(f"I could not find {input_}")
            sys.exit("Exiting...")

# Correct the savepath argument
savepath = args.savepath if args.savepath is not None else ""
savepath = path if savepath == "input" else savepath
savepath = savepath + "/" if savepath != "" and savepath[-1] != "/" else savepath
attrs = []
for a in args.attributes:
    op = a + output
    # Check if output file exist
    if os.path.exists(savepath + op):
        print(f"A file with the name {op} already exist.")
    else:
        if savepath != "":
            os.makedirs(savepath, exist_ok=True)
        print("Saving to", savepath + op)
        attrs.append(a)
if not attrs:
    sys.exit("All attributes files already exist. Exiting...")

print("Creating aggregated dataset...")
dataset = xr.open_mfdataset(the_input)
dataset = xr.decode_cf(dataset)
print("Finished creating aggregated dataset...")
# TREFHT: This is probably the correct one for global temperature, reference height
# temperature. SNOWHLND: land snow volume?
for a in attrs:
    print(f"Start creating file for attr {a}")
    ds = getattr(dataset, a)
    if args.year:
        ds = ds.chunk({"time": 12})
        r = ds.rolling(time=12)
        ds = r.mean()
    ds.to_netcdf(savepath + a + output)
    print(f"Finished creating {a + output}.")
