[tool.poetry]
name = "cesm-helper-scripts"
version = "0.2.1"
description = ""
authors = ["engeir <eirroleng@gmail.com>"]
license = "MIT"

[tool.poetry.scripts]
cplt = "cesm_helper_scripts.create_plots:main"
nc2np = "cesm_helper_scripts.nc_to_np:main"

[tool.poetry.dependencies]
python = ">3.7.1,<3.10"
rich = "^10.1.0"
matplotlib = "^3.4.1"
numpy = "^1.20.2"
xarray = "^0.17.0"
netCDF4 = "^1.5.6"
dask = "^2021.4.0"
nc-time-axis = "^1.2.0"
PyQt5 = "^5.15.4"
Cartopy = "^0.19.0"
scipy = "^1.7.1"
pykdtree = "^1.3.4"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
isort = "^5.8.0"
pre-commit = "^2.11.1"
mypy = "^0.812"
darglint = "^1.8.0"
pyupgrade = "^2.11.0"
flake8 = "^3.9.0"
pre-commit-hooks = "^3.4.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
