[tool.poetry]
name = "cesm-helper-scripts"
version = "0.3.2"
description = ""
authors = ["engeir <eirroleng@gmail.com>"]
license = "MIT"

[tool.poetry.scripts]
cplt = "cesm_helper_scripts.create_plots:main"
nc2np = "cesm_helper_scripts.nc_to_np:main"
remove-seasonal = "cesm_helper_scripts.remove_seasonal:remove_seasonal"

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
rich = "^10.1.0"
matplotlib = "^3.4.1"
numpy = "^1.20.2"
netCDF4 = "^1.5.6"
dask = "^2021.4.0"
nc-time-axis = "^1.2.0"
scipy = "^1.7.1"
pykdtree = "^1.3.4"
cftime = "^1.5.0"
animatplot = "^0.4.2"
cosmoplots = "^0.1.5"
Cartopy = { version = "^0.20.2", optional = true }
xmovie = { version = "^0.3.1", optional = true }
tqdm = "^4.63.1"
xarray = "^2022.3.0"
h5netcdf = "^1.0.2"
importlib-metadata = "^4.12.0"

[tool.poetry.extras]
cartopy = ["Cartopy"]
xmovie = ["xmovie"]

[tool.poetry.dev-dependencies]
isort = "^5.8.0"
pre-commit = "^2.11.1"
mypy = "^0.812"
darglint = "^1.8.0"
pyupgrade = "^2.11.0"
flake8 = "^3.9.0"
pre-commit-hooks = "^3.4.0"
pytest = "^6.2.5"
black = "^22.3.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry2conda]
name = "conda-cesm"

[tool.poetry2conda.dependencies]
cosmoplots = { channel = "pip" }
animatplot = { channel = "pip" }
nc-time-axis = { channel = "pip" }
Cartopy = { name = "Cartopy", channel = "conda-forge", version = "^0.20.2" }
xmovie = { name = "xmovie", channel = "conda-forge", version = "^0.3.1" }
