{% set name = "cesm-helper-scripts" %}
{% set version = "0.2.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  path: ..

build:
  number: 0
  entry_points:
    - cplt = cesm_helper_scripts.create_plots:main
    - nc2np = cesm_helper_scripts.nc_to_np:main
  script: python setup.py install --single-version-externally-managed --record=record.txt
  # script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - git
    - python>=3.8,<3.11
    - setuptools
  run:
  - python>=3.8,<3.11
  - rich>=10.1.0,<11.0.0
  - matplotlib>=3.4.1,<4.0.0
  - numpy>=1.20.2,<2.0.0
  - xarray>=0.19.0,<0.20.0
  - netCDF4>=1.5.6,<2.0.0
  - dask>=2021.4.0,<2022.0.0
  - scipy>=1.7.1,<2.0.0
  - pykdtree>=1.3.4,<2.0.0
  - cftime>=1.5.0,<2.0.0
  - conda-forge::Cartopy>=0.20.2,<0.21.0
  - nc-time-axis>=1.2.0,<2.0.0
  - animatplot>=0.4.2,<0.5.0
  - cosmoplots>=0.1.5,<0.2.0

test:
  imports:
    - cesm_helper_scripts
  commands:
    - cplt --help

about:
  home: "https://github.com/engeir/cesm-helper-scripts"
  license: "GNU General Public v3 (GPLv3)"
  license_family: GPL3
  license_file: 
  summary:
  doc_url: 
  dev_url: 
